package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BusinessObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Field1")
	private java.lang.Boolean field1;
	@org.kie.api.definition.type.Label("field2")
	private java.lang.String field2;

	@org.kie.api.definition.type.Label(value = "conditionField")
	private java.lang.Integer conditionField;

	public BusinessObject() {
	}

	public java.lang.Boolean getField1() {
		return this.field1;
	}

	public void setField1(java.lang.Boolean field1) {
		this.field1 = field1;
	}

	public java.lang.String getField2() {
		return this.field2;
	}

	public void setField2(java.lang.String field2) {
		this.field2 = field2;
	}

	public java.lang.Integer getConditionField() {
		return this.conditionField;
	}

	public void setConditionField(java.lang.Integer conditionField) {
		this.conditionField = conditionField;
	}

	public BusinessObject(java.lang.Boolean field1, java.lang.String field2,
			java.lang.Integer conditionField) {
		this.field1 = field1;
		this.field2 = field2;
		this.conditionField = conditionField;
	}

}